version: "3.7"

services:
  # lndg:
  #   image: ${LNDG_IMAGE}
  #   restart: on-failure
  #   stop_grace_period: 1m
  #   ports:
  #     - "8889:8889"
  #   volumes:
  #     - ${LND_DATADIR}:/root/.lnd:ro
  #     - ./lndg:/lndg/data
  #   command:
  #     - sh
  #     - -c
  #     - python initialize.py -net 'mainnet' -server '${LND_IP}:10009' -pw '${LNDG_PASSWORD}' -d && supervisord && python manage.py runserver 0.0.0.0:8889
  #   networks:
  #     umbrel: {}
  # lnshell:
  #   image: ${LNSHELL_IMAGE}
  #   restart: on-failure
  #   stop_grace_period: 1m
  #   ports:
  #     - 7681:7681
  #   volumes:
  #     - ${LND_DATADIR}:/lnd:ro
  #     - ./lightningshell:/data
  #   networks:
  #     umbrel: {}
  #   environment:
  #       APP_PASSWORD: ${LNSHELL_PASSWORD}
  #       BITCOIND_IP: ${BITCOIND_IP}
  #       BITCOIN_RPC_PORT: "8332"
  #       BITCOIN_RPC_USER: ${BITCOIND_RPC_USER}
  #       BITCOIN_RPC_PASS: ${BITCOIND_RPC_PASSWORD}
  #       LND_IP: ${LND_IP}
  #       LND_GRPC_PORT: 10009
  # thunderhub:
  #   image: ${THUNDERHUB_IMAGE}
  #   ports:
  #     - 3088:3088
  #   depends_on: [ lnd ]
  #   volumes:
  #     - ./thunderhub:/data
  #     - ${LND_DATADIR}/tls.cert:/lnd/tls.cert:ro
  #     - ${LND_DATADIR}/data/chain/bitcoin/mainnet/admin.macaroon:/lnd/admin.macaroon:ro
  #   networks:
  #     umbrel: {}
  #   environment:
  #     PORT: 3088
  #     HOST: 0.0.0.0
  #     NO_VERSION_CHECK: "true"
  #     ACCOUNT_CONFIG_PATH: "/data/thubConfig.yaml"
  #     TOR_PROXY_SERVER: "socks://tor:9050"
  #   profiles:
  #     - with_thunderhub
  # rtl:
  #   image: ${RTL_IMAGE}
  #   depends_on: [ lnd ]
  #   ports:
  #     - 3099:3099
  #   volumes:
  #     - ./rtl:/shared
  #     - ${LND_DATADIR}/tls.cert:/lnd/tls.cert:ro
  #     - ${LND_DATADIR}/data/chain/bitcoin/mainnet/admin.macaroon:/lnd/admin.macaroon:ro
  #   networks:
  #     umbrel: {}
  #   environment:
  #     PORT: 3099
  #     HOST: 0.0.0.0
  #     RTL_SSO: 0
  #     RTL_COOKIE_PATH: ''
  #     LOGOUT_REDIRECT_LINK: ''
  #     RTL_CONFIG_PATH: /shared/config
  #     BITCOIND_CONFIG_PATH: ''
  #     CHANNEL_BACKUP_PATH: /shared/backup
  #     LN_IMPLEMENTATION: "LND"
  #     LN_SERVER_URL: "https://${LND_IP}:8080"
  #     MACAROON_PATH: "/lnd"
  #     CONFIG_PATH: "/lnd/lnd.conf"
  #     APP_PASSWORD: ${RTL_PASSWORD}
  #   profiles:
  #     - with_rtl
  # bos:
  #   image: alexbosworth/balanceofsatoshis
  #   volumes:
  #     - './bos:/home/node/.bos'
  #     - '${LND_DATADIR}:/home/node/.lnd:ro'
  #   depends_on: [ lnd ]
  #   profiles:
  #     - with_bos
  lnd:
    container_name: lnd
    image: ${LND_IMAGE}
    user: 1000:1000
    restart: unless-stopped
    depends_on: [ tor ]
    ports:
      - 9735:9735
      - 10009:10009
      - 8080:8080
    volumes:
      - ${LND_DATADIR}:/data/.lnd
    environment:
      HOME: /data
    networks:
      umbrel:
        ipv4_address: ${LND_IP}
  bitcoin:
    container_name: bitcoin
    image: ${BITCOIND_IMAGE}
    restart: unless-stopped
    depends_on: [ tor ]
    volumes:
    - ./bitcoind/bitcoin.conf:/data/.bitcoin/bitcoin.conf
    - ${BITCOIND_DATADIR}:/data/.bitcoin
    ports:
      - 8333:8333
      - 8332:8332
    stop_grace_period: 15m30s
    networks:
      umbrel:
        ipv4_address: ${BITCOIND_IP}
  tor:
    container_name: tor
    image: ${TOR_IMAGE}
    user: toruser
    restart: unless-stopped
    volumes:
      - ${TOR_DATADIR}/torrc:/etc/tor/torrc
      - ${TOR_DATADIR}:/var/lib/tor
    networks:
      umbrel:
        ipv4_address: ${TOR_IP}
networks:
  umbrel:
    name: umbrel_main_network
    ipam:
      driver: default
      config:
        - subnet: "10.21.0.0/16"
 
